spring:
  application:
    name: member
  mvc:
    servlet:
      path: /member

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka