spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: account-service
          uri: lb://account
          predicates:
            - Path=/account/**
        - id: authentication-service
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: transaction-producer-service
          uri: lb://transaction-producer
          predicates:
            - Path=/transaction-producer/**
server:
  port: 9000


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka